[build.environment]
  NPM_FLAGS = "--version"

[build]
  base= "site/"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npm run build"
  publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"